
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import DB.input;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author the 12
 */
public class GuiInput extends javax.swing.JFrame {
  public Connection con; 
    private String sql; // variabel "sql" digunakan menampung hasil query database
    private Statement st; // object "st" dari class Statement
    private ResultSet rs; // object "rs" dari class Resulset
    private PreparedStatement ps; // object "ps" dari class PreparedStatement
    private DefaultTableModel dtm; 
    Object config;
    /**
     * Creates new form keamanan
     */
    public GuiInput() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jTabbedPane3 = new javax.swing.JTabbedPane();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jMenu1 = new javax.swing.JMenu();
        sliderPencahayaan2 = new javax.swing.JSlider();
        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        tabbedKeamanan = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jumlahStopKontak2 = new javax.swing.JTextField();
        cekStopKontakBaik2 = new javax.swing.JCheckBox();
        cekStopKontakBuruk2 = new javax.swing.JCheckBox();
        posisiStopKontak2 = new javax.swing.JTextField();
        jumlahLCD2 = new javax.swing.JTextField();
        cekLCDBaik2 = new javax.swing.JCheckBox();
        posisiLCD2 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        cekLCDkBuruk3 = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jumlahLampu = new javax.swing.JTextField();
        cekLampuBaik = new javax.swing.JCheckBox();
        cekKipasAnginburuk = new javax.swing.JCheckBox();
        posisiLampu = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jumlahKipasAngin = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        cekKipasAnginBaik = new javax.swing.JCheckBox();
        cekLampuBuruk1 = new javax.swing.JCheckBox();
        posisiKipasAngin = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jumlahAC = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        cekACBaik = new javax.swing.JCheckBox();
        cekACBuruk = new javax.swing.JCheckBox();
        posisiAC = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        SSID = new javax.swing.JTextField();
        Bandwith = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jumlahCCTV = new javax.swing.JTextField();
        cekCCTVBaik = new javax.swing.JCheckBox();
        cekCCTVBuruk = new javax.swing.JCheckBox();
        posisiCCTV = new javax.swing.JTextField();
        simpanSarana = new javax.swing.JButton();
        hapusSarana = new javax.swing.JButton();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel11 = new javax.swing.JPanel();
        jLabel55 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        ComboBoxKekokohan2 = new javax.swing.JComboBox();
        cekKunciPintuJendela2 = new javax.swing.JCheckBox();
        cekKunciPintuJendelaTidak2 = new javax.swing.JCheckBox();
        cekBahayaAman2 = new javax.swing.JCheckBox();
        cekBahayaBahaya2 = new javax.swing.JCheckBox();
        simpanKeamanan = new javax.swing.JButton();
        hapusKeamanan = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTabbedPane6 = new javax.swing.JTabbedPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        sliderPencahayaan = new javax.swing.JSlider();
        cekSirkulasiLancar = new javax.swing.JCheckBox();
        cekSirkulasiTerhambat = new javax.swing.JCheckBox();
        sliderPencahayaan1 = new javax.swing.JSlider();
        sliderPencahayaan3 = new javax.swing.JSlider();
        hapusKebersihan = new javax.swing.JButton();
        simpanKebersihan = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane7 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel12 = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        cekKebisinganBising = new javax.swing.JCheckBox();
        cekKebisinganTidak = new javax.swing.JCheckBox();
        cekBauBau = new javax.swing.JCheckBox();
        cekBauTidak = new javax.swing.JCheckBox();
        cekKebocoranBocor = new javax.swing.JCheckBox();
        cekKebocoranTidak = new javax.swing.JCheckBox();
        cekKerusakanRusak = new javax.swing.JCheckBox();
        cekKerusakanTidak = new javax.swing.JCheckBox();
        simpanKenyamanan = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        jPanel13 = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        cekLantaiBersih = new javax.swing.JCheckBox();
        cekDindingBersih = new javax.swing.JCheckBox();
        cekAtapBersih = new javax.swing.JCheckBox();
        cekJendelaBersih = new javax.swing.JCheckBox();
        cekPintuBersih = new javax.swing.JCheckBox();
        cekLantaiKotor = new javax.swing.JCheckBox();
        cekAtapKotor = new javax.swing.JCheckBox();
        cekPintuKotor = new javax.swing.JCheckBox();
        cekDindingKotor = new javax.swing.JCheckBox();
        cekJendelaKotor = new javax.swing.JCheckBox();
        buttonSelesai = new javax.swing.JButton();
        simpanKondisi = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        sliderPencahayaan2.setMajorTickSpacing(400);
        sliderPencahayaan2.setMaximum(400);
        sliderPencahayaan2.setMinimum(100);
        sliderPencahayaan2.setMinorTickSpacing(100);
        sliderPencahayaan2.setPaintTicks(true);
        sliderPencahayaan2.setAutoscrolls(true);
        sliderPencahayaan2.setDoubleBuffered(true);
        sliderPencahayaan2.setFocusable(false);

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 51, 204));
        jLabel11.setIcon(new javax.swing.ImageIcon("E:\\GAMBAR.otb\\Jpg.otb\\sasoRi_akaTsuki.jpg")); // NOI18N
        jLabel11.setText("jLabel11");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabbedKeamanan.setBackground(new java.awt.Color(51, 255, 51));
        tabbedKeamanan.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 255)));
        tabbedKeamanan.setForeground(new java.awt.Color(204, 0, 0));
        tabbedKeamanan.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        tabbedKeamanan.setFont(new java.awt.Font("Century Schoolbook", 3, 12)); // NOI18N

        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 255, 0));
        jLabel18.setText("Kondisi  Stop Kontak ");
        jPanel10.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 82, 181, 31));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 255, 0));
        jLabel19.setText("Jumlah Stop Kontak ");
        jPanel10.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 35, 181, 31));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 255, 0));
        jLabel20.setText("Posisi Stop Kontak ");
        jPanel10.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 119, 181, 31));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 255, 0));
        jLabel21.setText("Jumlah Kabel LCD");
        jPanel10.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 130, 31));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 255, 0));
        jLabel22.setText("Kondisi Kabel LCD");
        jPanel10.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 150, 31));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 255, 51));
        jLabel23.setText("Posisi Kabel LCD");
        jPanel10.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 120, 34));

        jLabel24.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 51, 255));
        jLabel24.setText("Stop Kontak");
        jPanel10.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 7, 169, -1));

        jumlahStopKontak2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahStopKontak2ActionPerformed(evt);
            }
        });
        jPanel10.add(jumlahStopKontak2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 50, -1));

        cekStopKontakBaik2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cekStopKontakBaik2.setForeground(new java.awt.Color(0, 51, 255));
        cekStopKontakBaik2.setText("Baik");
        cekStopKontakBaik2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekStopKontakBaik2ActionPerformed(evt);
            }
        });
        jPanel10.add(cekStopKontakBaik2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, -1, -1));

        cekStopKontakBuruk2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cekStopKontakBuruk2.setForeground(new java.awt.Color(0, 51, 255));
        cekStopKontakBuruk2.setText("Buruk");
        cekStopKontakBuruk2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekStopKontakBuruk2ActionPerformed(evt);
            }
        });
        jPanel10.add(cekStopKontakBuruk2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, -1, -1));

        posisiStopKontak2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posisiStopKontak2ActionPerformed(evt);
            }
        });
        jPanel10.add(posisiStopKontak2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 97, -1));
        jPanel10.add(jumlahLCD2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 50, -1));

        cekLCDBaik2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cekLCDBaik2.setForeground(new java.awt.Color(240, 240, 240));
        cekLCDBaik2.setText("Baik");
        cekLCDBaik2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekLCDBaik2ActionPerformed(evt);
            }
        });
        jPanel10.add(cekLCDBaik2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, -1, -1));

        posisiLCD2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posisiLCD2ActionPerformed(evt);
            }
        });
        jPanel10.add(posisiLCD2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 97, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 204));
        jLabel26.setText("Kabel LCD");
        jPanel10.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 169, -1));

        cekLCDkBuruk3.setForeground(new java.awt.Color(255, 255, 255));
        cekLCDkBuruk3.setText("Buruk");
        cekLCDkBuruk3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekLCDkBuruk3ActionPerformed(evt);
            }
        });
        jPanel10.add(cekLCDkBuruk3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("E:\\GAMBAR.otb\\Jpg.otb\\akaTsuki_HidaN.jpg")); // NOI18N
        jPanel10.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, -1));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 29, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel25.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel25.setText("Lampu");

        jLabel28.setText("Jumlah Kabel Lampu");

        jLabel29.setText("Posisi Kipas Angin");

        jLabel30.setText("Posisi Kabel Lampu");

        cekLampuBaik.setText("Baik");
        cekLampuBaik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekLampuBaikActionPerformed(evt);
            }
        });

        cekKipasAnginburuk.setText("Buruk");
        cekKipasAnginburuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekKipasAnginburukActionPerformed(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel31.setText("Kipas Angin");

        jLabel32.setText("Jumlah Kipas Angin");

        jumlahKipasAngin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahKipasAnginActionPerformed(evt);
            }
        });

        jLabel33.setText("Kondisi AC");

        jLabel34.setText("Kondisi Kabel Lampu");

        cekKipasAnginBaik.setText("Baik");
        cekKipasAnginBaik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekKipasAnginBaikActionPerformed(evt);
            }
        });

        cekLampuBuruk1.setText("Buruk");
        cekLampuBuruk1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekLampuBuruk1ActionPerformed(evt);
            }
        });

        posisiKipasAngin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posisiKipasAnginActionPerformed(evt);
            }
        });

        jLabel35.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel35.setText("AC");

        jLabel36.setText("Jumlah AC");

        jLabel37.setText("Kondisi kipas Angin");

        jumlahAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahACActionPerformed(evt);
            }
        });

        jLabel38.setText("Posisi AC");

        cekACBaik.setText("Baik");
        cekACBaik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekACBaikActionPerformed(evt);
            }
        });

        cekACBuruk.setText("Buruk");
        cekACBuruk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekACBurukActionPerformed(evt);
            }
        });

        posisiAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posisiACActionPerformed(evt);
            }
        });

        jLabel39.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel39.setText("CCTV");

        jLabel1.setText("Masukan SSID");

        jLabel3.setText("Masukan Bandwith");

        SSID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SSIDActionPerformed(evt);
            }
        });

        Bandwith.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BandwithActionPerformed(evt);
            }
        });

        jLabel40.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel40.setText("Koneksi");

        jLabel41.setText("Jumlah CCTV");

        jLabel42.setText("Kondisi CCTV");

        jLabel43.setText("Posisi CCTV");

        jumlahCCTV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahCCTVActionPerformed(evt);
            }
        });

        cekCCTVBaik.setText("Baik");
        cekCCTVBaik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekCCTVBaikActionPerformed(evt);
            }
        });

        cekCCTVBuruk.setText("Buruk");
        cekCCTVBuruk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekCCTVBurukActionPerformed(evt);
            }
        });

        posisiCCTV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posisiCCTVActionPerformed(evt);
            }
        });

        simpanSarana.setText("Simpan");
        simpanSarana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanSaranaActionPerformed(evt);
            }
        });

        hapusSarana.setText("hapus");
        hapusSarana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusSaranaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                                    .addComponent(jLabel34, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(cekLampuBaik)
                                        .addGap(92, 92, 92)
                                        .addComponent(cekLampuBuruk1))
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jumlahLampu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cekKipasAnginBaik)
                                            .addComponent(posisiLampu, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jumlahKipasAngin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(posisiKipasAngin, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jumlahAC, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cekACBaik)
                                            .addComponent(posisiAC, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(SSID, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Bandwith, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jumlahCCTV, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cekCCTVBaik)
                                            .addComponent(posisiCCTV, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(38, 38, 38))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                        .addComponent(hapusSarana)
                                        .addGap(18, 18, 18)))
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(simpanSarana)
                                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(cekKipasAnginburuk)
                                        .addComponent(cekACBuruk)
                                        .addComponent(cekCCTVBuruk)))))
                        .addContainerGap(603, Short.MAX_VALUE))))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 556, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel25)
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumlahLampu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cekLampuBaik)
                        .addComponent(cekLampuBuruk1))
                    .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(posisiLampu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(jLabel31)
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumlahKipasAngin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cekKipasAnginBaik)
                    .addComponent(cekKipasAnginburuk))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(posisiKipasAngin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(jLabel35)
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumlahAC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cekACBaik)
                    .addComponent(cekACBuruk))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(posisiAC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(SSID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Bandwith, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumlahCCTV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cekCCTVBaik)
                    .addComponent(cekCCTVBuruk))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(posisiCCTV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpanSarana)
                    .addComponent(hapusSarana))
                .addGap(119, 119, 119))
        );

        jScrollPane1.setViewportView(jPanel8);

        jTabbedPane2.addTab("INPUT", jScrollPane1);

        tabbedKeamanan.addTab("  Sarana ", jTabbedPane2);

        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel55.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(0, 0, 255));
        jLabel55.setText("Keamanan Ruang");
        jPanel11.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 178, 45));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 255, 0));
        jLabel14.setText("Kekokohan");
        jPanel11.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 100, -1));

        jLabel56.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(51, 255, 0));
        jLabel56.setText("Kunci Pintu & Jendela");
        jPanel11.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 154, -1));

        jLabel57.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(0, 255, 0));
        jLabel57.setText("Bahaya");
        jPanel11.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 103, 24));

        ComboBoxKekokohan2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ComboBoxKekokohan2.setForeground(new java.awt.Color(255, 255, 255));
        ComboBoxKekokohan2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "sangat kokoh", "kokoh", "kurang kokoh" }));
        ComboBoxKekokohan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxKekokohanActionPerformed(evt);
            }
        });
        jPanel11.add(ComboBoxKekokohan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, -1, -1));

        cekKunciPintuJendela2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cekKunciPintuJendela2.setForeground(new java.awt.Color(51, 51, 255));
        cekKunciPintuJendela2.setText("Ada");
        cekKunciPintuJendela2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekKunciPintuJendela2ActionPerformed(evt);
            }
        });
        jPanel11.add(cekKunciPintuJendela2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, -1, -1));

        cekKunciPintuJendelaTidak2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cekKunciPintuJendelaTidak2.setForeground(new java.awt.Color(51, 51, 255));
        cekKunciPintuJendelaTidak2.setText("Tidak Ada");
        cekKunciPintuJendelaTidak2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekKunciPintuJendelaTidak2ActionPerformed(evt);
            }
        });
        jPanel11.add(cekKunciPintuJendelaTidak2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, -1, -1));

        cekBahayaAman2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cekBahayaAman2.setForeground(new java.awt.Color(255, 255, 255));
        cekBahayaAman2.setText("Aman");
        cekBahayaAman2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekBahayaAman2ActionPerformed(evt);
            }
        });
        jPanel11.add(cekBahayaAman2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, -1, -1));

        cekBahayaBahaya2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cekBahayaBahaya2.setForeground(new java.awt.Color(255, 255, 255));
        cekBahayaBahaya2.setText("Bahaya");
        cekBahayaBahaya2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekBahayaBahaya2ActionPerformed(evt);
            }
        });
        jPanel11.add(cekBahayaBahaya2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, -1, -1));

        simpanKeamanan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        simpanKeamanan.setForeground(new java.awt.Color(0, 0, 255));
        simpanKeamanan.setText("simpan");
        simpanKeamanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanKeamananActionPerformed(evt);
            }
        });
        jPanel11.add(simpanKeamanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 288, -1, -1));

        hapusKeamanan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        hapusKeamanan.setForeground(new java.awt.Color(0, 0, 255));
        hapusKeamanan.setText("hapus");
        hapusKeamanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusKeamananActionPerformed(evt);
            }
        });
        jPanel11.add(hapusKeamanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 288, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon("E:\\GAMBAR.otb\\Jpg.otb\\Pain.jpg")); // NOI18N
        jPanel11.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -60, 510, 460));

        jScrollPane2.setViewportView(jPanel11);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
        );

        jTabbedPane5.addTab("INPUT", jPanel4);

        tabbedKeamanan.addTab(" Keamanan ", jTabbedPane5);

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel45.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(0, 51, 255));
        jLabel45.setText("Kebersihan Ruang");
        jPanel7.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 178, 45));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 255, 0));
        jLabel7.setText("kelancaran sirkulasi udara");
        jPanel7.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 67, 170, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 255, 0));
        jLabel8.setText("nilai pencahayan");
        jPanel7.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 124, 128, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 255, 0));
        jLabel9.setText("nilai kelembapan");
        jPanel7.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 176, 119, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 255, 0));
        jLabel10.setText("nilai suhu");
        jPanel7.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 225, 102, -1));

        sliderPencahayaan.setBackground(new java.awt.Color(102, 102, 255));
        sliderPencahayaan.setMajorTickSpacing(400);
        sliderPencahayaan.setMaximum(400);
        sliderPencahayaan.setMinimum(100);
        sliderPencahayaan.setMinorTickSpacing(100);
        sliderPencahayaan.setPaintTicks(true);
        sliderPencahayaan.setAutoscrolls(true);
        sliderPencahayaan.setDoubleBuffered(true);
        sliderPencahayaan.setFocusable(false);
        jPanel7.add(sliderPencahayaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 124, -1, 26));

        cekSirkulasiLancar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cekSirkulasiLancar.setForeground(new java.awt.Color(0, 51, 255));
        cekSirkulasiLancar.setText("Lancar");
        cekSirkulasiLancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekSirkulasiLancarActionPerformed(evt);
            }
        });
        jPanel7.add(cekSirkulasiLancar, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 63, -1, -1));

        cekSirkulasiTerhambat.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cekSirkulasiTerhambat.setForeground(new java.awt.Color(0, 51, 255));
        cekSirkulasiTerhambat.setText("Terhambat");
        cekSirkulasiTerhambat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekSirkulasiTerhambatActionPerformed(evt);
            }
        });
        jPanel7.add(cekSirkulasiTerhambat, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 63, -1, -1));

        sliderPencahayaan1.setBackground(new java.awt.Color(102, 51, 255));
        sliderPencahayaan1.setMajorTickSpacing(400);
        sliderPencahayaan1.setMaximum(400);
        sliderPencahayaan1.setMinimum(100);
        sliderPencahayaan1.setMinorTickSpacing(100);
        sliderPencahayaan1.setPaintTicks(true);
        sliderPencahayaan1.setAutoscrolls(true);
        sliderPencahayaan1.setDoubleBuffered(true);
        sliderPencahayaan1.setFocusable(false);
        jPanel7.add(sliderPencahayaan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 225, -1, -1));

        sliderPencahayaan3.setBackground(new java.awt.Color(102, 102, 255));
        sliderPencahayaan3.setMajorTickSpacing(400);
        sliderPencahayaan3.setMaximum(400);
        sliderPencahayaan3.setMinimum(100);
        sliderPencahayaan3.setMinorTickSpacing(100);
        sliderPencahayaan3.setPaintTicks(true);
        sliderPencahayaan3.setAutoscrolls(true);
        sliderPencahayaan3.setDoubleBuffered(true);
        sliderPencahayaan3.setFocusable(false);
        jPanel7.add(sliderPencahayaan3, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 176, -1, 30));

        hapusKebersihan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        hapusKebersihan.setForeground(new java.awt.Color(0, 0, 255));
        hapusKebersihan.setText("hapus");
        hapusKebersihan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusKebersihanActionPerformed(evt);
            }
        });
        jPanel7.add(hapusKebersihan, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 321, -1, -1));

        simpanKebersihan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        simpanKebersihan.setForeground(new java.awt.Color(0, 51, 255));
        simpanKebersihan.setText("simpan");
        simpanKebersihan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanKebersihanActionPerformed(evt);
            }
        });
        jPanel7.add(simpanKebersihan, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 321, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("E:\\GAMBAR.otb\\Jpg.otb\\aKaTsuki_kaKuzU.jpg")); // NOI18N
        jPanel7.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 430, -1));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 584, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1130, Short.MAX_VALUE))
        );

        jScrollPane3.setViewportView(jPanel6);

        jTabbedPane6.addTab("INPUT", jScrollPane3);

        tabbedKeamanan.addTab(" Kebersihan ", jTabbedPane6);

        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel47.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(0, 0, 255));
        jLabel47.setText("Kenyamanan Ruang");
        jPanel12.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 220, 45));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 255, 0));
        jLabel15.setText("Kebisingan ");
        jPanel12.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 67, 128, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 255, 0));
        jLabel16.setText("Bau");
        jPanel12.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 108, 128, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 255, 0));
        jLabel17.setText("Kebocoran");
        jPanel12.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 149, 128, -1));

        jLabel48.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(0, 255, 0));
        jLabel48.setText("Kerusakan");
        jPanel12.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 128, -1));

        cekKebisinganBising.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cekKebisinganBising.setForeground(new java.awt.Color(0, 51, 255));
        cekKebisinganBising.setText("Bising");
        cekKebisinganBising.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekKebisinganBisingActionPerformed(evt);
            }
        });
        jPanel12.add(cekKebisinganBising, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 63, -1, -1));

        cekKebisinganTidak.setBackground(new java.awt.Color(255, 255, 255));
        cekKebisinganTidak.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cekKebisinganTidak.setForeground(new java.awt.Color(0, 51, 255));
        cekKebisinganTidak.setText("Tenang");
        cekKebisinganTidak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekKebisinganTidakActionPerformed(evt);
            }
        });
        jPanel12.add(cekKebisinganTidak, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 63, -1, -1));

        cekBauBau.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cekBauBau.setForeground(new java.awt.Color(0, 51, 255));
        cekBauBau.setText("Bau");
        cekBauBau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekBauBauActionPerformed(evt);
            }
        });
        jPanel12.add(cekBauBau, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 104, -1, -1));

        cekBauTidak.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cekBauTidak.setForeground(new java.awt.Color(0, 51, 255));
        cekBauTidak.setText("Harum");
        cekBauTidak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekBauTidakActionPerformed(evt);
            }
        });
        jPanel12.add(cekBauTidak, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 104, -1, -1));

        cekKebocoranBocor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cekKebocoranBocor.setForeground(new java.awt.Color(255, 255, 255));
        cekKebocoranBocor.setText("Bocor");
        cekKebocoranBocor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekKebocoranBocorActionPerformed(evt);
            }
        });
        jPanel12.add(cekKebocoranBocor, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 145, -1, -1));

        cekKebocoranTidak.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cekKebocoranTidak.setForeground(new java.awt.Color(255, 255, 255));
        cekKebocoranTidak.setText("Tidak Bocor");
        cekKebocoranTidak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekKebocoranTidakActionPerformed(evt);
            }
        });
        jPanel12.add(cekKebocoranTidak, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 145, -1, -1));

        cekKerusakanRusak.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cekKerusakanRusak.setForeground(new java.awt.Color(255, 255, 255));
        cekKerusakanRusak.setText("Rusak");
        cekKerusakanRusak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekKerusakanRusakActionPerformed(evt);
            }
        });
        jPanel12.add(cekKerusakanRusak, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 186, -1, -1));

        cekKerusakanTidak.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cekKerusakanTidak.setForeground(new java.awt.Color(255, 255, 255));
        cekKerusakanTidak.setText("Baik");
        cekKerusakanTidak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekKerusakanTidakActionPerformed(evt);
            }
        });
        jPanel12.add(cekKerusakanTidak, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 186, -1, -1));

        simpanKenyamanan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        simpanKenyamanan.setForeground(new java.awt.Color(51, 0, 255));
        simpanKenyamanan.setText("simpan");
        simpanKenyamanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanKenyamananActionPerformed(evt);
            }
        });
        jPanel12.add(simpanKenyamanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 287, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon("E:\\GAMBAR.otb\\Jpg.otb\\Kisame.jpg")); // NOI18N
        jPanel12.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 490, -1));

        jScrollPane4.setViewportView(jPanel12);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
        );

        jTabbedPane7.addTab("INPUT", jPanel3);

        tabbedKeamanan.addTab(" Kenyamanan ", jTabbedPane7);

        jLayeredPane1.setBackground(new java.awt.Color(0, 255, 0));
        jLayeredPane1.setBorder(new javax.swing.border.MatteBorder(null));
        jLayeredPane1.setForeground(new java.awt.Color(0, 255, 51));
        jLayeredPane1.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setForeground(new java.awt.Color(255, 255, 255));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel49.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(0, 0, 255));
        jLabel49.setText("Kondisi Ruang");
        jPanel13.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 178, 45));

        jLabel50.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(0, 255, 0));
        jLabel50.setText("Lantai");
        jPanel13.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 63, 128, -1));

        jLabel51.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(0, 255, 0));
        jLabel51.setText("Dinding");
        jPanel13.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 108, 128, -1));

        jLabel52.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(0, 255, 0));
        jLabel52.setText("Atap");
        jPanel13.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 149, 119, -1));

        jLabel53.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(0, 255, 0));
        jLabel53.setText("Pintu");
        jPanel13.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 102, -1));

        jLabel54.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(0, 255, 0));
        jLabel54.setText("Jendela");
        jPanel13.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 231, 102, -1));

        jButton1.setText("SELESAI");
        jPanel13.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(772, 1440, -1, -1));

        cekLantaiBersih.setBackground(new java.awt.Color(255, 255, 255));
        cekLantaiBersih.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cekLantaiBersih.setForeground(new java.awt.Color(255, 255, 255));
        cekLantaiBersih.setText("Bersih");
        cekLantaiBersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekLantaiBersihActionPerformed(evt);
            }
        });
        jPanel13.add(cekLantaiBersih, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 63, -1, -1));

        cekDindingBersih.setBackground(new java.awt.Color(255, 255, 255));
        cekDindingBersih.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cekDindingBersih.setForeground(new java.awt.Color(255, 255, 255));
        cekDindingBersih.setText("Bersih");
        cekDindingBersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekDindingBersihActionPerformed(evt);
            }
        });
        jPanel13.add(cekDindingBersih, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 104, -1, -1));

        cekAtapBersih.setBackground(new java.awt.Color(255, 255, 255));
        cekAtapBersih.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cekAtapBersih.setForeground(new java.awt.Color(255, 255, 255));
        cekAtapBersih.setText("Bersih");
        cekAtapBersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekAtapBersihActionPerformed(evt);
            }
        });
        jPanel13.add(cekAtapBersih, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 145, -1, -1));

        cekJendelaBersih.setBackground(new java.awt.Color(255, 255, 255));
        cekJendelaBersih.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cekJendelaBersih.setForeground(new java.awt.Color(255, 255, 255));
        cekJendelaBersih.setText("Bersih");
        cekJendelaBersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekJendelaBersihActionPerformed(evt);
            }
        });
        jPanel13.add(cekJendelaBersih, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 227, -1, -1));

        cekPintuBersih.setBackground(new java.awt.Color(255, 255, 255));
        cekPintuBersih.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cekPintuBersih.setForeground(new java.awt.Color(255, 255, 255));
        cekPintuBersih.setText("Bersih");
        cekPintuBersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekPintuBersihActionPerformed(evt);
            }
        });
        jPanel13.add(cekPintuBersih, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 186, -1, -1));

        cekLantaiKotor.setBackground(new java.awt.Color(255, 255, 255));
        cekLantaiKotor.setForeground(new java.awt.Color(255, 255, 255));
        cekLantaiKotor.setText("Kotor");
        cekLantaiKotor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekLantaiKotorActionPerformed(evt);
            }
        });
        jPanel13.add(cekLantaiKotor, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 63, -1, -1));

        cekAtapKotor.setBackground(new java.awt.Color(255, 255, 255));
        cekAtapKotor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cekAtapKotor.setForeground(new java.awt.Color(255, 255, 255));
        cekAtapKotor.setText("Kotor");
        cekAtapKotor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekAtapKotorActionPerformed(evt);
            }
        });
        jPanel13.add(cekAtapKotor, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 145, -1, -1));

        cekPintuKotor.setBackground(new java.awt.Color(255, 255, 255));
        cekPintuKotor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cekPintuKotor.setForeground(new java.awt.Color(255, 255, 255));
        cekPintuKotor.setText("Kotor");
        cekPintuKotor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekPintuKotorActionPerformed(evt);
            }
        });
        jPanel13.add(cekPintuKotor, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 186, -1, -1));

        cekDindingKotor.setBackground(new java.awt.Color(255, 255, 255));
        cekDindingKotor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cekDindingKotor.setForeground(new java.awt.Color(255, 255, 255));
        cekDindingKotor.setText("Kotor");
        cekDindingKotor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekDindingKotorActionPerformed(evt);
            }
        });
        jPanel13.add(cekDindingKotor, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 104, -1, -1));

        cekJendelaKotor.setBackground(new java.awt.Color(255, 255, 255));
        cekJendelaKotor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cekJendelaKotor.setForeground(new java.awt.Color(255, 255, 255));
        cekJendelaKotor.setText("Kotor");
        cekJendelaKotor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekJendelaKotorActionPerformed(evt);
            }
        });
        jPanel13.add(cekJendelaKotor, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 227, -1, -1));

        buttonSelesai.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        buttonSelesai.setForeground(new java.awt.Color(0, 0, 255));
        buttonSelesai.setText("SELESAI");
        buttonSelesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSelesaiActionPerformed(evt);
            }
        });
        jPanel13.add(buttonSelesai, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, -1, -1));

        simpanKondisi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        simpanKondisi.setForeground(new java.awt.Color(0, 0, 255));
        simpanKondisi.setText("simpan");
        simpanKondisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanKondisiActionPerformed(evt);
            }
        });
        jPanel13.add(simpanKondisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, -1, -1));

        jLabel12.setForeground(new java.awt.Color(255, 102, 102));
        jLabel12.setIcon(new javax.swing.ImageIcon("E:\\GAMBAR.otb\\Jpg.otb\\Zetzu.jpg")); // NOI18N
        jLabel12.setText("jLabel12");
        jPanel13.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 20, -1, -1));

        jScrollPane5.setViewportView(jPanel13);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
        );
        jLayeredPane1.setLayer(jScrollPane5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        tabbedKeamanan.addTab(" Kondisi ", jLayeredPane1);

        jPanel1.add(tabbedKeamanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 548, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void cekDindingKotorActionPerformed(java.awt.event.ActionEvent evt) {                                                
    cekDindingBersih.setSelected(false);        // TODO add your handling code here:
    }                                               

    private void cekDindingBersihActionPerformed(java.awt.event.ActionEvent evt) {                                                 
    cekDindingKotor.setSelected(false);        // TODO add your handling code here:
    }                                                

    private void posisiCCTVActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void cekCCTVBurukActionPerformed(java.awt.event.ActionEvent evt) {                                             
        cekCCTVBaik.setSelected(false);// TODO add your handling code here:
    }                                            

    private void cekCCTVBaikActionPerformed(java.awt.event.ActionEvent evt) {                                            
        cekCCTVBuruk.setSelected(false);        // TODO add your handling code here:
    }                                           

    private void jumlahCCTVActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void BandwithActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void SSIDActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
    }                                    

    private void posisiACActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void cekACBurukActionPerformed(java.awt.event.ActionEvent evt) {                                           
        cekACBaik.setSelected(false);     // TODO a   dd your handling code here:
    }                                          

    private void cekACBaikActionPerformed(java.awt.event.ActionEvent evt) {                                          
        cekACBuruk.setSelected(false);        // TODO add your handling code here:
    }                                         

    private void jumlahACActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void posisiKipasAnginActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
    }                                                

    private void cekLampuBuruk1ActionPerformed(java.awt.event.ActionEvent evt) {                                               
        cekLampuBaik.setSelected(false);        // TODO add your handling code here:
    }                                              

    private void cekKipasAnginBaikActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        cekKipasAnginburuk.setSelected(false);   // TODO add your handling code here:
    }                                                 

    private void jumlahKipasAnginActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
    }                                                

    private void cekKipasAnginburukActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        cekKipasAnginBaik.setSelected(false);        // TODO add your handling code here:
    }                                                  

    private void cekLampuBaikActionPerformed(java.awt.event.ActionEvent evt) {                                             
        cekLampuBuruk1.setSelected(false);        // TODO add your handling code here:
    }                                            

    private void cekKunciPintuJendela2ActionPerformed(java.awt.event.ActionEvent evt) {                                                      
    cekKunciPintuJendelaTidak2.setSelected(false);        // TODO add your handling code here:
    }                                                     

    private void cekKunciPintuJendelaTidak2ActionPerformed(java.awt.event.ActionEvent evt) {                                                           
    cekKunciPintuJendela2.setSelected(false);        // TODO add your handling code here:
    }                                                          

    private void cekBahayaAman2ActionPerformed(java.awt.event.ActionEvent evt) {                                               
    cekBahayaBahaya2.setSelected(false);        // TODO add your handling code here:
    }                                              

    private void cekBahayaBahaya2ActionPerformed(java.awt.event.ActionEvent evt) {                                                 
    cekBahayaAman2.setSelected(false);        // TODO add your handling code here:
    }                                                

    private void cekKebisinganBisingActionPerformed(java.awt.event.ActionEvent evt) {                                                    
    cekKebisinganTidak.setSelected(false);        // TODO add your handling code here:
    }                                                   

    private void cekKebisinganTidakActionPerformed(java.awt.event.ActionEvent evt) {                                                   
    cekKebisinganBising.setSelected(false);        // TODO add your handling code here:
    }                                                  

    private void cekBauBauActionPerformed(java.awt.event.ActionEvent evt) {                                          
    cekBauTidak.setSelected(false);        // TODO add your handling code here:
    }                                         

    private void cekBauTidakActionPerformed(java.awt.event.ActionEvent evt) {                                            
    cekBauBau.setSelected(false);        // TODO add your handling code here:
    }                                           

    private void cekKebocoranBocorActionPerformed(java.awt.event.ActionEvent evt) {                                                  
    cekKebocoranTidak.setSelected(false);        // TODO add your handling code here:
    }                                                 

    private void cekKebocoranTidakActionPerformed(java.awt.event.ActionEvent evt) {                                                  
    cekKebocoranBocor.setSelected(false);        // TODO add your handling code here:
    }                                                 

    private void cekKerusakanRusakActionPerformed(java.awt.event.ActionEvent evt) {                                                  
    cekKerusakanTidak.setSelected(false);        // TODO add your handling code here:
    }                                                 

    private void cekKerusakanTidakActionPerformed(java.awt.event.ActionEvent evt) {                                                  
    cekKerusakanRusak.setSelected(false);        // TODO add your handling code here:
    }                                                 

    private void cekLantaiBersihActionPerformed(java.awt.event.ActionEvent evt) {                                                
    cekLantaiKotor.setSelected(false);        // TODO add your handling code here:
    }                                               

    private void cekLantaiKotorActionPerformed(java.awt.event.ActionEvent evt) {                                               
    cekLantaiBersih.setSelected(false);        // TODO add your handling code here:
    }                                              

    private void cekAtapBersihActionPerformed(java.awt.event.ActionEvent evt) {                                              
    cekAtapKotor.setSelected(false);        // TODO add your handling code here:
    }                                             

    private void cekAtapKotorActionPerformed(java.awt.event.ActionEvent evt) {                                             
    cekLantaiBersih.setSelected(false);        // TODO add your handling code here:
    }                                            

    private void cekPintuBersihActionPerformed(java.awt.event.ActionEvent evt) {                                               
    cekPintuKotor.setSelected(false);        // TODO add your handling code here:
    }                                              

    private void cekPintuKotorActionPerformed(java.awt.event.ActionEvent evt) {                                              
    cekPintuBersih.setSelected(false);        // TODO add your handling code here:
    }                                             

    private void cekJendelaBersihActionPerformed(java.awt.event.ActionEvent evt) {                                                 
    cekJendelaKotor.setSelected(false);        // TODO add your handling code here:
    }                                                

    private void cekJendelaKotorActionPerformed(java.awt.event.ActionEvent evt) {                                                
    cekJendelaBersih.setSelected(false);        // TODO add your handling code here:
    }                                               

    private void buttonSelesaiActionPerformed(java.awt.event.ActionEvent evt) {                                              
        GuiOutput qaz=new GuiOutput();
        qaz.setVisible(true); 
        this.dispose();// TODO add your handling code here:
    }                                             

    private void simpanSaranaActionPerformed(java.awt.event.ActionEvent evt) {                                             
      try {
             String sql="insert into sarana utama values('"+jumlahAC.getText()
                     +"','"+jumlahCCTV.getText()
                     +"','"+jumlahKipasAngin.getText()
                     +"','"+jumlahLCD2.getText()
                     +"','"+jumlahLampu.getText()
                     +"','"+jumlahStopKontak2.getText()
                     +"','"+cekACBaik.getSelectedObjects()
                     +"','"+cekACBuruk.getSelectedObjects()
                     +"','"+cekCCTVBaik.getSelectedObjects()
                     +"','"+cekCCTVBuruk.getSelectedObjects()
                     +"','"+cekKipasAnginBaik.getSelectedObjects()
                     +"','"+cekKipasAnginburuk.getSelectedObjects()
                     +"','"+cekLCDBaik2.getSelectedObjects()
                     +"','"+cekLCDkBuruk3.getSelectedObjects()
                     +"','"+cekLampuBaik.getSelectedObjects()
                     +"','"+cekLampuBuruk1.getSelectedObjects()
                     +"','"+cekStopKontakBaik2.getSelectedObjects()
                     +"','"+cekStopKontakBuruk2.getSelectedObjects()
                     +"','"+posisiAC.getText()
                     +"','"+posisiCCTV.getText()
                     +"','"+posisiKipasAngin.getText()
                     +"','"+posisiLCD2.getText()
                     +"','"+posisiLampu.getText()
                     +"','"+posisiStopKontak2.getText()+"')"; 
            st=con.createStatement(); 
            st.executeUpdate(sql); 
            JOptionPane.showMessageDialog(null, "DATA SUKSES TERSIMPAN"); 
           
           } catch (Exception e)
           {
            JOptionPane.showMessageDialog(null, "DATA GAGAL TERSIMPAN"); 
//indikator yang sitampilkan pada comand dialog jika data gagal tersimpan
            } // TODO add your handling code here:
    }                                            

    private void hapusSaranaActionPerformed(java.awt.event.ActionEvent evt) {                                            
try{
   
    jumlahAC.setText("");
    jumlahCCTV.setText("");
    jumlahKipasAngin.setText("");
    jumlahLCD2.setText("");
    jumlahLampu.setText("");
    jumlahStopKontak2.setText("");
    /*cekACBaik.setText("");
    cekACBuruk.setText("");
    cekCCTVBaik.setText("");
    cekCCTVBuruk.setText("");
    cekKipasAnginBaik.setText("");
    cekKipasAnginburuk.setText("");
    cekLCDBaik2.setText("");
    cekLCDkBuruk3.setText("");
    cekLampuBaik.setText("");
    cekLampuBuruk1.setText("");
    cekStopKontakBaik2.setText("");
    cekStopKontakBuruk2.setText("");*/
    posisiAC.setText("");
    posisiCCTV.setText("");
    posisiKipasAngin.setText("");
    posisiLCD2.setText("");
    posisiLampu.setText("");
    posisiStopKontak2.setText("");
    SSID.setText("");
    Bandwith.setText("");
    
    
    
}catch (Exception e){
}        // TODO add your handling code here:
    }                                           

    private void ComboBoxKekokohanActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
    }                                                 

    private void hapusKeamananActionPerformed(java.awt.event.ActionEvent evt) {                                              
try{
   /*
    cekKunciPintuJendela2.setText("");
    cekKunciPintuJendelaTidak2.setText("");
    cekBahayaAman2.setText("");
    cekBahayaBahaya2.setText("");*/
}catch (Exception e){
}        // TODO add your handling code here:
    }                                             

    private void simpanKeamananActionPerformed(java.awt.event.ActionEvent evt) {                                               
try {
             String sql="insert into tbjava ',' keamanan ruang values('"+ComboBoxKekokohan2.getActionCommand()
                                             +"','"+cekKunciPintuJendela2.getSelectedObjects()
                     +"','"+cekKunciPintuJendelaTidak2.getSelectedObjects()
                     +"','"+cekBahayaAman2.getSelectedObjects()
                     +"','"+cekBahayaBahaya2.getSelectedObjects()+"')"; 
            st=con.createStatement(); 
            st.executeUpdate(sql); 
            JOptionPane.showMessageDialog(null, "DATA SUKSES TERSIMPAN"); 
           
           } catch (Exception e)
           {
            JOptionPane.showMessageDialog(null, "DATA GAGAL TERSIMPAN"); 
//indikator yang sitampilkan pada comand dialog jika data gagal tersimpan
            }        // TODO add your handling code here:
    }                                              

    private void simpanKenyamananActionPerformed(java.awt.event.ActionEvent evt) {                                                 
       try {
             String sql="insert into tbjava','kenyaman ruang values('"+cekKebisinganBising.getSelectedObjects()
                                             +"','"+cekKebisinganTidak.getSelectedObjects()
                     +"','"+cekBauBau.getSelectedObjects()
                     +"','"+cekBauTidak.getSelectedObjects()
                     +"','"+cekKebocoranBocor.getSelectedObjects()
                     +"','"+cekKebocoranTidak.getSelectedObjects()
                     +"','"+cekKerusakanRusak.getSelectedObjects()
                     +"','"+cekKerusakanTidak.getSelectedObjects()
                     
                     
                    +"')"; 
            st=con.createStatement(); 
            st.executeUpdate(sql); 
            JOptionPane.showMessageDialog(null, "DATA SUKSES TERSIMPAN"); 
           
           } catch (Exception e)
           {
            JOptionPane.showMessageDialog(null, "DATA GAGAL TERSIMPAN"); 
//indikator yang sitampilkan pada comand dialog jika data gagal tersimpan
            } // TODO add your handling code here:
    }                                                

    private void simpanKondisiActionPerformed(java.awt.event.ActionEvent evt) {                                              
       try {
             String sql="insert into tbjava','kondisi ruang values('"+cekLantaiBersih.getSelectedObjects()
                                             +"','"+cekLantaiKotor.getSelectedObjects()
                     +"','"+cekDindingBersih.getSelectedObjects()
                     +"','"+cekDindingKotor.getSelectedObjects()
                     +"','"+cekAtapBersih.getSelectedObjects()
                     +"','"+cekAtapKotor.getSelectedObjects()
                     +"','"+cekPintuBersih.getSelectedObjects()
                     +"','"+cekPintuKotor.getSelectedObjects()
                     
                     
                    +"')"; 
            st=con.createStatement(); 
            st.executeUpdate(sql); 
            JOptionPane.showMessageDialog(null, "DATA SUKSES TERSIMPAN"); 
           
           } catch (Exception e)
           {
            JOptionPane.showMessageDialog(null, "DATA GAGAL TERSIMPAN"); 
//indikator yang sitampilkan pada comand dialog jika data gagal tersimpan
            } // TODO add your handling code here:
    }                                             

    private void cekLCDkBuruk3ActionPerformed(java.awt.event.ActionEvent evt) {                                              
        cekLCDBaik2.setSelected(false);        // TODO add your handling code here:
    }                                             

    private void cekLCDBaik2ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        cekLCDkBuruk3.setSelected(false);   // TODO add your handling code here:
    }                                           

    private void cekStopKontakBuruk2ActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        cekStopKontakBaik2.setSelected(false);    // TODO add your handling code here:
    }                                                   

    private void cekStopKontakBaik2ActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        cekStopKontakBuruk2.setSelected(false);        // TODO add your handling code here:
    }                                                  

    private void jumlahStopKontak2ActionPerformed(java.awt.event.ActionEvent evt) {                                                  

    }                                                 

    private void posisiLCD2ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void posisiStopKontak2ActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
    }                                                 

    private void simpanKebersihanActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        try {
            String sql="insert into tbjava','kebersihan ruang values('"+cekSirkulasiLancar.getSelectedObjects()
            +"','"+cekSirkulasiTerhambat.getSelectedObjects()
            +"','"+sliderPencahayaan.getAutoscrolls()
            +"','"+sliderPencahayaan1.getAutoscrolls()
            +"','"+sliderPencahayaan3.getAutoscrolls()+"')";
            st=con.createStatement();
            st.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "DATA SUKSES TERSIMPAN");

        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "DATA GAGAL TERSIMPAN");
            //indikator yang sitampilkan pada comand dialog jika data gagal tersimpan
        }  // TODO add your handling code here:
    }                                                

    private void hapusKebersihanActionPerformed(java.awt.event.ActionEvent evt) {                                                
        try{

            cekSirkulasiLancar.setActionCommand("");
            cekSirkulasiTerhambat.setActionCommand("");

        }catch (Exception e){
        }        // TODO add your handling code here:
        // TODO add your handling code here:
    }                                               

    private void cekSirkulasiTerhambatActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        cekSirkulasiLancar.setSelected(false);        // TODO add your handling code here:
    }                                                     

    private void cekSirkulasiLancarActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        cekSirkulasiTerhambat.setSelected(false);        // TODO add your handling code here:
    }                                                  

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiInput().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTextField Bandwith;
    private javax.swing.JComboBox ComboBoxKekokohan2;
    private javax.swing.JTextField SSID;
    private javax.swing.JButton buttonSelesai;
    private javax.swing.JCheckBox cekACBaik;
    private javax.swing.JCheckBox cekACBuruk;
    private javax.swing.JCheckBox cekAtapBersih;
    private javax.swing.JCheckBox cekAtapKotor;
    private javax.swing.JCheckBox cekBahayaAman2;
    private javax.swing.JCheckBox cekBahayaBahaya2;
    private javax.swing.JCheckBox cekBauBau;
    private javax.swing.JCheckBox cekBauTidak;
    private javax.swing.JCheckBox cekCCTVBaik;
    private javax.swing.JCheckBox cekCCTVBuruk;
    private javax.swing.JCheckBox cekDindingBersih;
    private javax.swing.JCheckBox cekDindingKotor;
    private javax.swing.JCheckBox cekJendelaBersih;
    private javax.swing.JCheckBox cekJendelaKotor;
    private javax.swing.JCheckBox cekKebisinganBising;
    private javax.swing.JCheckBox cekKebisinganTidak;
    private javax.swing.JCheckBox cekKebocoranBocor;
    private javax.swing.JCheckBox cekKebocoranTidak;
    private javax.swing.JCheckBox cekKerusakanRusak;
    private javax.swing.JCheckBox cekKerusakanTidak;
    private javax.swing.JCheckBox cekKipasAnginBaik;
    private javax.swing.JCheckBox cekKipasAnginburuk;
    private javax.swing.JCheckBox cekKunciPintuJendela2;
    private javax.swing.JCheckBox cekKunciPintuJendelaTidak2;
    private javax.swing.JCheckBox cekLCDBaik2;
    private javax.swing.JCheckBox cekLCDkBuruk3;
    private javax.swing.JCheckBox cekLampuBaik;
    private javax.swing.JCheckBox cekLampuBuruk1;
    private javax.swing.JCheckBox cekLantaiBersih;
    private javax.swing.JCheckBox cekLantaiKotor;
    private javax.swing.JCheckBox cekPintuBersih;
    private javax.swing.JCheckBox cekPintuKotor;
    private javax.swing.JCheckBox cekSirkulasiLancar;
    private javax.swing.JCheckBox cekSirkulasiTerhambat;
    private javax.swing.JCheckBox cekStopKontakBaik2;
    private javax.swing.JCheckBox cekStopKontakBuruk2;
    private javax.swing.JButton hapusKeamanan;
    private javax.swing.JButton hapusKebersihan;
    private javax.swing.JButton hapusSarana;
    private javax.swing.JButton jButton1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTabbedPane jTabbedPane6;
    private javax.swing.JTabbedPane jTabbedPane7;
    private javax.swing.JTextField jumlahAC;
    private javax.swing.JTextField jumlahCCTV;
    private javax.swing.JTextField jumlahKipasAngin;
    private javax.swing.JTextField jumlahLCD2;
    private javax.swing.JTextField jumlahLampu;
    private javax.swing.JTextField jumlahStopKontak2;
    private javax.swing.JTextField posisiAC;
    private javax.swing.JTextField posisiCCTV;
    private javax.swing.JTextField posisiKipasAngin;
    private javax.swing.JTextField posisiLCD2;
    private javax.swing.JTextField posisiLampu;
    private javax.swing.JTextField posisiStopKontak2;
    private javax.swing.JButton simpanKeamanan;
    private javax.swing.JButton simpanKebersihan;
    private javax.swing.JButton simpanKenyamanan;
    private javax.swing.JButton simpanKondisi;
    private javax.swing.JButton simpanSarana;
    private javax.swing.JSlider sliderPencahayaan;
    private javax.swing.JSlider sliderPencahayaan1;
    private javax.swing.JSlider sliderPencahayaan2;
    private javax.swing.JSlider sliderPencahayaan3;
    private javax.swing.JTabbedPane tabbedKeamanan;
    // End of variables declaration                   
}
